In [179]:
import pandas as pd
import numpy as np
from scipy import linalg

## Creating a dataset containing the returns of all quarters in one column for each fund. So creating a dataframe with 56X7 dimensions

In [180]:
df1 = pd.ExcelFile(r'C:\Users\samas\Downloads\NYU Spring 2021-4 data.xlsx')

In [181]:
df2 = pd.read_excel(df1, 'VBTLX', header= 1)
df2.set_index("Unnamed: 0", inplace = True)
df2.dropna(axis = 1, inplace = True)

l = []
for index, row in df2.iterrows():
    current_row = row.values
    l.append(current_row)
l = np.array(l)
l = np.concatenate(l)

In [182]:
df3 = pd.read_excel(df1, 'VWILX', header = 1)
df3.set_index("Unnamed: 0", inplace = True)
df3.dropna(axis = 1, inplace = True)

m = []
for index, row in df3.iterrows():
    current_row = row.values
    m.append(current_row)
m = np.array(m)
m = np.concatenate(m)
    

In [183]:
df4 = pd.read_excel(df1, 'VGPMX', header = 1)
df4.set_index("Unnamed: 0", inplace = True)
df4.dropna(axis = 1, inplace = True)

n = []
for index, row in df4.iterrows():
    current_row = row.values
    n.append(current_row)
n = np.array(n)
n = np.concatenate(n)

In [184]:
df5 = pd.read_excel(df1, 'VTSAX', header = 1)
df5.set_index("Unnamed: 0", inplace = True)
df5.dropna(axis = 1, inplace = True)

o = []
for index, row in df5.iterrows():
    current_row = row.values
    o.append(current_row)
o = np.array(o)
o = np.concatenate(o)

In [185]:
df6 = pd.read_excel(df1, 'VTRIX', header = 1)

df6.set_index("Unnamed: 0", inplace = True)
df6.dropna(axis = 1, inplace = True)

p = []
for index, row in df6.iterrows():
    current_row = row.values
    p.append(current_row)
p = np.array(p)
p = np.concatenate(p)


In [186]:
df7 = pd.read_excel(df1, 'VGSLX', header = 1)
df7.set_index("Unnamed: 0", inplace = True)
df7.dropna(axis = 1, inplace = True)

q = []
for index, row in df7.iterrows():
    current_row = row.values
    q.append(current_row)
q = np.array(q)
q = np.concatenate(q)

In [187]:
df8 = pd.read_excel(df1, 'VMRXX', header = 1)
df8.set_index("Unnamed: 0", inplace = True)
df8.dropna(axis = 1, inplace = True)
r = []
for index, row in df8.iterrows():
    current_row = row.values
    r.append(current_row)
r = np.array(r)
r = np.concatenate(r)

In [188]:
all_rets = pd.DataFrame(np.column_stack([l,m,n,o,p,q,r]), columns = ['VBTLX', 'VWILX', 'VGPMX', 'VTSAX', 'VTRIX', 'VGSLX', 'VMRXX'])

## Dataset with 56X7 dimensions

In [189]:
all_rets

VBTLX   VWILX   VGPMX   VTSAX   VTRIX   VGSLX   VMRXX
0   0.0327 -0.1552 -0.2528 -0.2087 -0.2630 -0.2410  0.0040
1   0.0298  0.3301  0.2319  0.2208  0.1508  0.1346  0.0013
2   0.0061  0.1627  0.0928  0.0920  0.0399  0.0133  0.0003
3   0.0067  0.2226  0.1653  0.1469  0.2357  0.0926  0.0001
4   0.0294  0.1492  0.1004  0.1404  0.0944  0.1728  0.0062
5   0.0307  0.0323  0.0321  0.0409  0.0242  0.0173  0.0062
6   0.0243 -0.0302 -0.0075  0.0109 -0.0125  0.0740  0.0056
7   0.0003  0.1429  0.0703  0.0901  0.0877  0.0062  0.0047
8  -0.0147  0.0339 -0.0930 -0.0060 -0.0063 -0.0811  0.0039
9  -0.0017  0.0071  0.0115  0.0391 -0.0320  0.0883  0.0048
10  0.0003 -0.0151 -0.1469  0.0709  0.0099  0.0052  0.0054
11  0.0161 -0.1476 -0.1346 -0.1426 -0.1201 -0.0644  0.0059
12  0.0091  0.1267  0.1056  0.0579  0.0806  0.0096  0.0021
13  0.0148  0.1026 -0.0183  0.0303  0.0577  0.0161  0.0026
14  0.0073  0.1068  0.0216  0.0454  0.0672  0.0089  0.0029
15  0.0040  0.0413  0.0259  0.0634  0.0490  0.0139  0.0032
16  0.0309 -0.0201  0.3157  0.0094 -0.0051  0.0627  0.0011
17  0.0236  0.0052  0.3484  0.0269  0.0013  0.0680  0.0013
18  0.0041  0.1083  0.0145  0.0440  0.0604 -0.0147  0.0014
19 -0.0317 -0.0670 -0.1630  0.0412 -0.0111 -0.0297  0.0017
20  0.0165  0.0549 -0.0368  0.0179  0.0418  0.0472  0.0002
21 -0.0179  0.0118 -0.0058  0.0008  0.0122 -0.1046  0.0002
22  0.0118 -0.1299 -0.2190 -0.0727 -0.1341  0.0201  0.0003
23 -0.0060  0.0709 -0.0564  0.0626  0.0246  0.0704  0.0005
24  0.0191 -0.0074  0.0716  0.0203 -0.0008  0.0998  0.0001
25  0.0197  0.0314  0.0532  0.0486  0.0503  0.0702  0.0001
26  0.0017 -0.0491 -0.1345 -0.0003 -0.0574 -0.0313  0.0001
27  0.0172 -0.0293 -0.0931  0.0524 -0.0568  0.1430  0.0001
28 -0.0006  0.0312 -0.1544  0.1102  0.0215  0.0807  0.0002
29 -0.0242 -0.0215 -0.2300  0.0279 -0.0003 -0.0161  0.0001
30  0.0054  0.1368  0.0299  0.0627  0.1181 -0.0300  0.0002
31 -0.0019  0.0733 -0.0327  0.1010  0.0698 -0.0071  0.0001
32  0.0027  0.1396  0.0254  0.1291  0.1224  0.1072  0.0003
33  0.0216 -0.0780 -0.1930 -0.0315 -0.0780  0.0373  0.0003
34  0.0155  0.0707  0.1222  0.0624  0.0722 -0.0002  0.0003
35  0.0013  0.0682 -0.0629  0.0018  0.0830  0.0249  0.0003
36  0.0027  0.0327  0.0029  0.0636  0.0187  0.0649  0.0005
37  0.0227  0.0162 -0.0512 -0.0002  0.0070  0.0358  0.0004
38  0.0401 -0.2230 -0.1764 -0.1523 -0.2073 -0.1455  0.0003
39  0.0097  0.0599 -0.0009  0.1214  0.0505  0.1524  0.0003
40  0.0172  0.0255  0.0397  0.0603  0.0150  0.1007  0.0004
41  0.0361 -0.1216 -0.1130 -0.1130 -0.1596 -0.0398  0.0004
42  0.0245  0.1986  0.2325  0.1164  0.1800  0.1315  0.0006
43 -0.0133  0.0725  0.2093  0.1168  0.0661  0.0744  0.0005
44  0.0036 -0.1023  0.0211 -0.1067 -0.1289 -0.3203  0.0037
45  0.0178  0.2711  0.2621  0.1692  0.2494  0.2996  0.0015
46  0.0370  0.1925  0.2409  0.1653  0.2075  0.3463  0.0009
47  0.0010  0.0427  0.1034  0.0584  0.0179  0.0911  0.0007
48  0.0221 -0.0903  0.0846 -0.0948 -0.0829  0.0214  0.0100
49 -0.0107 -0.0166  0.1147 -0.0154 -0.0151 -0.0533  0.0062
50 -0.0039 -0.1974 -0.4256 -0.0852 -0.1886  0.0536  0.0059
51  0.0440 -0.2316 -0.3666 -0.2272 -0.2051 -0.3815  0.0068
52  0.0147  0.0296  0.0885  0.0136  0.0325  0.0339  0.0130
53 -0.0063  0.0888  0.1322  0.0607  0.0833 -0.0935  0.0131
54  0.0295  0.0408  0.0717  0.0156  0.0270  0.0240  0.0133
55  0.0310 -0.0037  0.0307 -0.0332 -0.0193 -0.1288  0.0125

## Creating Dataset for Q7

In [190]:
new_funds = pd.DataFrame([all_rets['VTSAX']+ all_rets['VTRIX'] + all_rets['VWILX'], all_rets.VBTLX, all_rets.VGPMX, all_rets.VGSLX, all_rets.VMRXX])

In [191]:
new_funds = new_funds.T
new_funds.rename(columns = {'Unnamed 0' : 'three_funds'}, inplace=True)
new_funds

three_funds   VBTLX   VGPMX   VGSLX   VMRXX
0       -0.6269  0.0327 -0.2528 -0.2410  0.0040
1        0.7017  0.0298  0.2319  0.1346  0.0013
2        0.2946  0.0061  0.0928  0.0133  0.0003
3        0.6052  0.0067  0.1653  0.0926  0.0001
4        0.3840  0.0294  0.1004  0.1728  0.0062
5        0.0974  0.0307  0.0321  0.0173  0.0062
6       -0.0318  0.0243 -0.0075  0.0740  0.0056
7        0.3207  0.0003  0.0703  0.0062  0.0047
8        0.0216 -0.0147 -0.0930 -0.0811  0.0039
9        0.0142 -0.0017  0.0115  0.0883  0.0048
10       0.0657  0.0003 -0.1469  0.0052  0.0054
11      -0.4103  0.0161 -0.1346 -0.0644  0.0059
12       0.2652  0.0091  0.1056  0.0096  0.0021
13       0.1906  0.0148 -0.0183  0.0161  0.0026
14       0.2194  0.0073  0.0216  0.0089  0.0029
15       0.1537  0.0040  0.0259  0.0139  0.0032
16      -0.0158  0.0309  0.3157  0.0627  0.0011
17       0.0334  0.0236  0.3484  0.0680  0.0013
18       0.2127  0.0041  0.0145 -0.0147  0.0014
19      -0.0369 -0.0317 -0.1630 -0.0297  0.0017
20       0.1146  0.0165 -0.0368  0.0472  0.0002
21       0.0248 -0.0179 -0.0058 -0.1046  0.0002
22      -0.3367  0.0118 -0.2190  0.0201  0.0003
23       0.1581 -0.0060 -0.0564  0.0704  0.0005
24       0.0121  0.0191  0.0716  0.0998  0.0001
25       0.1303  0.0197  0.0532  0.0702  0.0001
26      -0.1068  0.0017 -0.1345 -0.0313  0.0001
27      -0.0337  0.0172 -0.0931  0.1430  0.0001
28       0.1629 -0.0006 -0.1544  0.0807  0.0002
29       0.0061 -0.0242 -0.2300 -0.0161  0.0001
30       0.3176  0.0054  0.0299 -0.0300  0.0002
31       0.2441 -0.0019 -0.0327 -0.0071  0.0001
32       0.3911  0.0027  0.0254  0.1072  0.0003
33      -0.1875  0.0216 -0.1930  0.0373  0.0003
34       0.2053  0.0155  0.1222 -0.0002  0.0003
35       0.1530  0.0013 -0.0629  0.0249  0.0003
36       0.1150  0.0027  0.0029  0.0649  0.0005
37       0.0230  0.0227 -0.0512  0.0358  0.0004
38      -0.5826  0.0401 -0.1764 -0.1455  0.0003
39       0.2318  0.0097 -0.0009  0.1524  0.0003
40       0.1008  0.0172  0.0397  0.1007  0.0004
41      -0.3942  0.0361 -0.1130 -0.0398  0.0004
42       0.4950  0.0245  0.2325  0.1315  0.0006
43       0.2554 -0.0133  0.2093  0.0744  0.0005
44      -0.3379  0.0036  0.0211 -0.3203  0.0037
45       0.6897  0.0178  0.2621  0.2996  0.0015
46       0.5653  0.0370  0.2409  0.3463  0.0009
47       0.1190  0.0010  0.1034  0.0911  0.0007
48      -0.2680  0.0221  0.0846  0.0214  0.0100
49      -0.0471 -0.0107  0.1147 -0.0533  0.0062
50      -0.4712 -0.0039 -0.4256  0.0536  0.0059
51      -0.6639  0.0440 -0.3666 -0.3815  0.0068
52       0.0757  0.0147  0.0885  0.0339  0.0130
53       0.2328 -0.0063  0.1322 -0.0935  0.0131
54       0.0834  0.0295  0.0717  0.0240  0.0133
55      -0.0562  0.0310  0.0307 -0.1288  0.0125

## Questions 2,3,4,5

In [192]:
#Calculating Excess returns for each quarter
all_rets[['VBTLX', 'VWILX', 'VGPMX', 'VTSAX', 'VTRIX', 'VGSLX']] = all_rets[['VBTLX', 'VWILX', 'VGPMX', 'VTSAX', 'VTRIX', 'VGSLX']] - all_rets.VMRXX.values[:, None]

In [193]:
all_rets.mean()

VBTLX    0.008293
VWILX    0.025632
VGPMX    0.002591
VTSAX    0.024654
VTRIX    0.010468
VGSLX    0.017355
VMRXX    0.002841
dtype: float64

In [194]:
mean_excess = np.array(all_rets.mean())
mean_excess = mean_excess[0:6]

In [195]:
mean_excess

array([0.00829286, 0.02563214, 0.00259107, 0.02465357, 0.01046786,
       0.01735536])

In [196]:
all_rets # excess returs
all_rets = all_rets - all_rets.mean() # demeaned excess returns
all_rets.drop(columns = 'VMRXX', inplace = True)

In [198]:
all_rets #Dataset with demeaned excess returns and no riskfree assets.

VBTLX     VWILX     VGPMX     VTSAX     VTRIX     VGSLX
0   0.020407 -0.184832 -0.259391 -0.237354 -0.277468 -0.262355
1   0.020207  0.303168  0.228009  0.194846  0.139032  0.115945
2  -0.002493  0.136768  0.089909  0.067046  0.029132 -0.004355
3  -0.001693  0.196868  0.162609  0.122146  0.225132  0.075145
4   0.014907  0.117368  0.091609  0.109546  0.077732  0.149245
5   0.016207  0.000468  0.023309  0.010046  0.007532 -0.006255
6   0.010407 -0.061432 -0.015691 -0.019354 -0.028568  0.051045
7  -0.012693  0.112568  0.063009  0.060746  0.072532 -0.015855
8  -0.026893  0.004368 -0.099491 -0.034554 -0.020668 -0.102355
9  -0.014793 -0.023332  0.004109  0.009646 -0.047268  0.066145
10 -0.013393 -0.046132 -0.154891  0.040846 -0.005968 -0.017555
11  0.001907 -0.179132 -0.143091 -0.173154 -0.136468 -0.087655
12 -0.001293  0.098968  0.100909  0.031146  0.068032 -0.009855
13  0.003907  0.074368 -0.023491  0.003046  0.044632 -0.003855
14 -0.003893  0.078268  0.016109  0.017846  0.053832 -0.011355
15 -0.007493  0.012468  0.020109  0.035546  0.035332 -0.006655
16  0.021507 -0.046832  0.312009 -0.016354 -0.016668  0.044245
17  0.014007 -0.021732  0.344509  0.000946 -0.010468  0.049345
18 -0.005593  0.081268  0.010509  0.017946  0.048532 -0.033455
19 -0.041693 -0.094332 -0.167291  0.014846 -0.023268 -0.048755
20  0.008007  0.029068 -0.039591 -0.006954  0.031132  0.029645
21 -0.026393 -0.014032 -0.008591 -0.024054  0.001532 -0.122155
22  0.003207 -0.155832 -0.221891 -0.097654 -0.144868  0.002445
23 -0.014793  0.044768 -0.059491  0.037446  0.013632  0.052545
24  0.010707 -0.033132  0.068909 -0.004454 -0.011368  0.082345
25  0.011307  0.005668  0.050509  0.023846  0.039732  0.052745
26 -0.006693 -0.074832 -0.137191 -0.025054 -0.067968 -0.048755
27  0.008807 -0.055032 -0.095791  0.027646 -0.067368  0.125545
28 -0.009093  0.005368 -0.157191  0.085346  0.010832  0.063145
29 -0.032593 -0.047232 -0.232691  0.003146 -0.010868 -0.033555
30 -0.003093  0.110968  0.027109  0.037846  0.107432 -0.047555
31 -0.010293  0.047568 -0.035391  0.076246  0.059232 -0.024555
32 -0.005893  0.113668  0.022509  0.104146  0.111632  0.089545
33  0.013007 -0.103932 -0.195891 -0.056454 -0.088768  0.019645
34  0.006907  0.044768  0.119309  0.037446  0.061432 -0.017855
35 -0.007293  0.042268 -0.065791 -0.023154  0.072232  0.007245
36 -0.006093  0.006568 -0.000191  0.038446  0.007732  0.047045
37  0.014007 -0.009832 -0.054191 -0.025254 -0.003868  0.018045
38  0.031507 -0.248932 -0.179291 -0.177254 -0.218068 -0.163155
39  0.001107  0.033968 -0.003791  0.096446  0.039732  0.134745
40  0.008507 -0.000532  0.036709  0.035246  0.004132  0.082945
41  0.027407 -0.147632 -0.115991 -0.138054 -0.170468 -0.057555
42  0.015607  0.172368  0.229309  0.091146  0.168932  0.113545
43 -0.022093  0.046368  0.206209  0.091646  0.055132  0.056545
44 -0.008393 -0.131632  0.014809 -0.135054 -0.143068 -0.341355
45  0.008007  0.243968  0.258009  0.143046  0.237432  0.280745
46  0.027807  0.165968  0.237409  0.139746  0.196132  0.328045
47 -0.007993  0.016368  0.100109  0.033046  0.006732  0.073045
48  0.003807 -0.125932  0.072009 -0.129454 -0.103368 -0.005955
49 -0.025193 -0.048432  0.105909 -0.046254 -0.031768 -0.076855
50 -0.018093 -0.228932 -0.434091 -0.115754 -0.204968  0.030345
51  0.028907 -0.264032 -0.375991 -0.258654 -0.222368 -0.405655
52 -0.006593 -0.009032  0.072909 -0.024054  0.009032  0.003545
53 -0.027693  0.050068  0.116509  0.022946  0.059732 -0.123955
54  0.007907  0.001868  0.055809 -0.022354  0.003232 -0.006655
55  0.010207 -0.041832  0.015609 -0.070354 -0.042268 -0.158655

## Solution to Q2

In [200]:
# Covariance matrix of six excess returns series
cv_excess_demeaned_rets = all_rets.cov()
cv_excess_demeaned_rets

VBTLX     VWILX     VGPMX     VTSAX     VTRIX     VGSLX
VBTLX  0.000267 -0.000104  0.000371 -0.000267 -0.000206  0.000205
VWILX -0.000104  0.013382  0.012735  0.009422  0.011486  0.008609
VGPMX  0.000371  0.012735  0.024573  0.008791  0.011567  0.009361
VTSAX -0.000267  0.009422  0.008791  0.008276  0.008635  0.008387
VTRIX -0.000206  0.011486  0.011567  0.008635  0.011034  0.008398
VGSLX  0.000205  0.008609  0.009361  0.008387  0.008398  0.014565

## Solution to Q3

In [201]:
# Correlation Matrix of excess retursn series for six funds
corr_excess_demeaned_rets = all_rets.corr()
corr_excess_demeaned_rets

VBTLX     VWILX     VGPMX     VTSAX     VTRIX     VGSLX
VBTLX  1.000000 -0.054876  0.144621 -0.179247 -0.119770  0.103700
VWILX -0.054876  1.000000  0.702316  0.895305  0.945259  0.616657
VGPMX  0.144621  0.702316  1.000000  0.616488  0.702513  0.494842
VTSAX -0.179247  0.895305  0.616488  1.000000  0.903618  0.763959
VTRIX -0.119770  0.945259  0.702513  0.903618  1.000000  0.662511
VGSLX  0.103700  0.616657  0.494842  0.763959  0.662511  1.000000

## Solution to Q4

In [202]:
# Computing Inverse Covariance matrix
cv_inv = np.linalg.inv(cv_excess_demeaned_rets)
cv_inv

array([[ 5.71991043e+03, -7.74049376e+02, -1.77405533e+02,
         1.21273195e+03,  5.47133713e+02, -5.22652416e+02],
       [-7.74049376e+02,  9.59353946e+02, -3.60453841e+01,
        -5.39421232e+02, -6.84224639e+02,  1.72164187e+02],
       [-1.77405533e+02, -3.60453841e+01,  9.11903693e+01,
         1.68642302e+01, -7.25227384e+01, -2.70763521e+00],
       [ 1.21273195e+03, -5.39421232e+02,  1.68642302e+01,
         1.32820358e+03, -2.00069937e+02, -3.58536631e+02],
       [ 5.47133713e+02, -6.84224639e+02, -7.25227384e+01,
        -2.00069937e+02,  1.10596273e+03, -7.91563225e+01],
       [-5.22652416e+02,  1.72164187e+02, -2.70763521e+00,
        -3.58536631e+02, -7.91563225e+01,  2.28092966e+02]])

## Solution to Q5

In [119]:
Sharpe_weights = mean_excess.dot(cv_inv) # computing the portfolio optimal weights

In [120]:
Sharpe_weights

array([53.68885748,  0.60476561, -2.54922455, 20.70231423, -7.91791843,
       -5.6375311 ])

In [203]:
normalized_weights = []
for i in Sharpe_weights:
    i = i/sum(Sharpe_weights)
    normalized_weights.append(i)

## Optimal Sharpe portfolio weights

In [204]:
normalized_weights

[0.9116608223827289,
 0.010269190727560589,
 -0.04328697352538991,
 0.35153455862657973,
 -0.1344497976590481,
 -0.09572780055243119]

## Calculating Portfolio Variance

In [123]:
portfolio_var = np.array(normalized_weights).dot(cv_excess_demeaned_rets).dot(np.array(normalized_weights).T)

## Portfolio Standard Deviation

In [124]:
portfolio_sd = np.sqrt(portfolio_var)
portfolio_sd

0.015033127006948642

## Portfolio Expected returns based on mean excess historical returns

In [125]:
portfolio_excess_rets = np.array(mean_excess).dot(np.array(normalized_weights))

## Computing Portfolio Sharpe Ratio

In [205]:
portfolio_sharpe = portfolio_excess_rets/ portfolio_sd
portfolio_sharpe 

0.885319839902642

## Solution to Q6

In [206]:
adviser_weights = [0.3, 0.15, 0.1, 0.2, 0.15, 0.1 ]

In [207]:
# Calculating Standard Deviation of Adviser Portfolio
adviser_sd = np.sqrt(np.array(adviser_weights).dot(cv_excess_demeaned_rets).dot(np.array(adviser_weights).T))

In [208]:
# Calculating Adviser portfolio Variance
adviser_var = np.array(adviser_weights).dot(cv_excess_demeaned_rets).dot(np.array(adviser_weights).T)

In [209]:
# Getting the expected returns of six funds according to Advisers Expected return from his/ her portfolio.
adv_exp_rets = (0.06/ adviser_var)*(np.array(adviser_weights)).dot(cv_excess_demeaned_rets)

In [210]:
adv_exp_rets

array([0.00045672, 0.09290353, 0.10723352, 0.07224393, 0.08474134,
       0.08044114])

In [133]:
mean_excess

array([0.00829286, 0.02563214, 0.00259107, 0.02465357, 0.01046786,
       0.01735536])

In [211]:
#Advisers Sharpe Ratio
adviser_sharpe = adv_exp_rets.dot(adviser_weights)/ adviser_sd
adviser_sharpe

0.8498548025201312

From the results above we can say that the expected returns of the six funds calculated by the adviser are not that reasonable, since based on historical performance of the funds, the returns should be close to mean excess returns calculated . But the returns used by adviser are quite dfferent based on his own assumptions which we do not know. And the shape ratio of the advisers portfolio is lower than the one computed in previous question. This says that the adviser is getting low return for more risk exposure compared to our portfolio.

## Solution to Q7

In [212]:
new_funds

three_funds   VBTLX   VGPMX   VGSLX   VMRXX
0       -0.6269  0.0327 -0.2528 -0.2410  0.0040
1        0.7017  0.0298  0.2319  0.1346  0.0013
2        0.2946  0.0061  0.0928  0.0133  0.0003
3        0.6052  0.0067  0.1653  0.0926  0.0001
4        0.3840  0.0294  0.1004  0.1728  0.0062
5        0.0974  0.0307  0.0321  0.0173  0.0062
6       -0.0318  0.0243 -0.0075  0.0740  0.0056
7        0.3207  0.0003  0.0703  0.0062  0.0047
8        0.0216 -0.0147 -0.0930 -0.0811  0.0039
9        0.0142 -0.0017  0.0115  0.0883  0.0048
10       0.0657  0.0003 -0.1469  0.0052  0.0054
11      -0.4103  0.0161 -0.1346 -0.0644  0.0059
12       0.2652  0.0091  0.1056  0.0096  0.0021
13       0.1906  0.0148 -0.0183  0.0161  0.0026
14       0.2194  0.0073  0.0216  0.0089  0.0029
15       0.1537  0.0040  0.0259  0.0139  0.0032
16      -0.0158  0.0309  0.3157  0.0627  0.0011
17       0.0334  0.0236  0.3484  0.0680  0.0013
18       0.2127  0.0041  0.0145 -0.0147  0.0014
19      -0.0369 -0.0317 -0.1630 -0.0297  0.0017
20       0.1146  0.0165 -0.0368  0.0472  0.0002
21       0.0248 -0.0179 -0.0058 -0.1046  0.0002
22      -0.3367  0.0118 -0.2190  0.0201  0.0003
23       0.1581 -0.0060 -0.0564  0.0704  0.0005
24       0.0121  0.0191  0.0716  0.0998  0.0001
25       0.1303  0.0197  0.0532  0.0702  0.0001
26      -0.1068  0.0017 -0.1345 -0.0313  0.0001
27      -0.0337  0.0172 -0.0931  0.1430  0.0001
28       0.1629 -0.0006 -0.1544  0.0807  0.0002
29       0.0061 -0.0242 -0.2300 -0.0161  0.0001
30       0.3176  0.0054  0.0299 -0.0300  0.0002
31       0.2441 -0.0019 -0.0327 -0.0071  0.0001
32       0.3911  0.0027  0.0254  0.1072  0.0003
33      -0.1875  0.0216 -0.1930  0.0373  0.0003
34       0.2053  0.0155  0.1222 -0.0002  0.0003
35       0.1530  0.0013 -0.0629  0.0249  0.0003
36       0.1150  0.0027  0.0029  0.0649  0.0005
37       0.0230  0.0227 -0.0512  0.0358  0.0004
38      -0.5826  0.0401 -0.1764 -0.1455  0.0003
39       0.2318  0.0097 -0.0009  0.1524  0.0003
40       0.1008  0.0172  0.0397  0.1007  0.0004
41      -0.3942  0.0361 -0.1130 -0.0398  0.0004
42       0.4950  0.0245  0.2325  0.1315  0.0006
43       0.2554 -0.0133  0.2093  0.0744  0.0005
44      -0.3379  0.0036  0.0211 -0.3203  0.0037
45       0.6897  0.0178  0.2621  0.2996  0.0015
46       0.5653  0.0370  0.2409  0.3463  0.0009
47       0.1190  0.0010  0.1034  0.0911  0.0007
48      -0.2680  0.0221  0.0846  0.0214  0.0100
49      -0.0471 -0.0107  0.1147 -0.0533  0.0062
50      -0.4712 -0.0039 -0.4256  0.0536  0.0059
51      -0.6639  0.0440 -0.3666 -0.3815  0.0068
52       0.0757  0.0147  0.0885  0.0339  0.0130
53       0.2328 -0.0063  0.1322 -0.0935  0.0131
54       0.0834  0.0295  0.0717  0.0240  0.0133
55      -0.0562  0.0310  0.0307 -0.1288  0.0125

Calculating the excess returns

In [213]:
new_funds[['three_funds','VBTLX', 'VGPMX', 'VGSLX']] = new_funds[['three_funds','VBTLX', 'VGPMX', 'VGSLX']] - new_funds.VMRXX.values[:, None]

In [214]:
new_funds

three_funds   VBTLX   VGPMX   VGSLX   VMRXX
0       -0.6309  0.0287 -0.2568 -0.2450  0.0040
1        0.7004  0.0285  0.2306  0.1333  0.0013
2        0.2943  0.0058  0.0925  0.0130  0.0003
3        0.6051  0.0066  0.1652  0.0925  0.0001
4        0.3778  0.0232  0.0942  0.1666  0.0062
5        0.0912  0.0245  0.0259  0.0111  0.0062
6       -0.0374  0.0187 -0.0131  0.0684  0.0056
7        0.3160 -0.0044  0.0656  0.0015  0.0047
8        0.0177 -0.0186 -0.0969 -0.0850  0.0039
9        0.0094 -0.0065  0.0067  0.0835  0.0048
10       0.0603 -0.0051 -0.1523 -0.0002  0.0054
11      -0.4162  0.0102 -0.1405 -0.0703  0.0059
12       0.2631  0.0070  0.1035  0.0075  0.0021
13       0.1880  0.0122 -0.0209  0.0135  0.0026
14       0.2165  0.0044  0.0187  0.0060  0.0029
15       0.1505  0.0008  0.0227  0.0107  0.0032
16      -0.0169  0.0298  0.3146  0.0616  0.0011
17       0.0321  0.0223  0.3471  0.0667  0.0013
18       0.2113  0.0027  0.0131 -0.0161  0.0014
19      -0.0386 -0.0334 -0.1647 -0.0314  0.0017
20       0.1144  0.0163 -0.0370  0.0470  0.0002
21       0.0246 -0.0181 -0.0060 -0.1048  0.0002
22      -0.3370  0.0115 -0.2193  0.0198  0.0003
23       0.1576 -0.0065 -0.0569  0.0699  0.0005
24       0.0120  0.0190  0.0715  0.0997  0.0001
25       0.1302  0.0196  0.0531  0.0701  0.0001
26      -0.1069  0.0016 -0.1346 -0.0314  0.0001
27      -0.0338  0.0171 -0.0932  0.1429  0.0001
28       0.1627 -0.0008 -0.1546  0.0805  0.0002
29       0.0060 -0.0243 -0.2301 -0.0162  0.0001
30       0.3174  0.0052  0.0297 -0.0302  0.0002
31       0.2440 -0.0020 -0.0328 -0.0072  0.0001
32       0.3908  0.0024  0.0251  0.1069  0.0003
33      -0.1878  0.0213 -0.1933  0.0370  0.0003
34       0.2050  0.0152  0.1219 -0.0005  0.0003
35       0.1527  0.0010 -0.0632  0.0246  0.0003
36       0.1145  0.0022  0.0024  0.0644  0.0005
37       0.0226  0.0223 -0.0516  0.0354  0.0004
38      -0.5829  0.0398 -0.1767 -0.1458  0.0003
39       0.2315  0.0094 -0.0012  0.1521  0.0003
40       0.1004  0.0168  0.0393  0.1003  0.0004
41      -0.3946  0.0357 -0.1134 -0.0402  0.0004
42       0.4944  0.0239  0.2319  0.1309  0.0006
43       0.2549 -0.0138  0.2088  0.0739  0.0005
44      -0.3416 -0.0001  0.0174 -0.3240  0.0037
45       0.6882  0.0163  0.2606  0.2981  0.0015
46       0.5644  0.0361  0.2400  0.3454  0.0009
47       0.1183  0.0003  0.1027  0.0904  0.0007
48      -0.2780  0.0121  0.0746  0.0114  0.0100
49      -0.0533 -0.0169  0.1085 -0.0595  0.0062
50      -0.4771 -0.0098 -0.4315  0.0477  0.0059
51      -0.6707  0.0372 -0.3734 -0.3883  0.0068
52       0.0627  0.0017  0.0755  0.0209  0.0130
53       0.2197 -0.0194  0.1191 -0.1066  0.0131
54       0.0701  0.0162  0.0584  0.0107  0.0133
55      -0.0687  0.0185  0.0182 -0.1413  0.0125

In [140]:
new_funds_mean_excess = np.array(new_funds.mean())

In [223]:
new_funds_mean_excess


array([0.06643571, 0.00829286, 0.00259107, 0.01735536, 0.00284107])

In [141]:
new_funds = new_funds - new_funds.mean()

In [215]:
#demeaned excess returns 
new_funds

three_funds   VBTLX   VGPMX   VGSLX   VMRXX
0       -0.6309  0.0287 -0.2568 -0.2450  0.0040
1        0.7004  0.0285  0.2306  0.1333  0.0013
2        0.2943  0.0058  0.0925  0.0130  0.0003
3        0.6051  0.0066  0.1652  0.0925  0.0001
4        0.3778  0.0232  0.0942  0.1666  0.0062
5        0.0912  0.0245  0.0259  0.0111  0.0062
6       -0.0374  0.0187 -0.0131  0.0684  0.0056
7        0.3160 -0.0044  0.0656  0.0015  0.0047
8        0.0177 -0.0186 -0.0969 -0.0850  0.0039
9        0.0094 -0.0065  0.0067  0.0835  0.0048
10       0.0603 -0.0051 -0.1523 -0.0002  0.0054
11      -0.4162  0.0102 -0.1405 -0.0703  0.0059
12       0.2631  0.0070  0.1035  0.0075  0.0021
13       0.1880  0.0122 -0.0209  0.0135  0.0026
14       0.2165  0.0044  0.0187  0.0060  0.0029
15       0.1505  0.0008  0.0227  0.0107  0.0032
16      -0.0169  0.0298  0.3146  0.0616  0.0011
17       0.0321  0.0223  0.3471  0.0667  0.0013
18       0.2113  0.0027  0.0131 -0.0161  0.0014
19      -0.0386 -0.0334 -0.1647 -0.0314  0.0017
20       0.1144  0.0163 -0.0370  0.0470  0.0002
21       0.0246 -0.0181 -0.0060 -0.1048  0.0002
22      -0.3370  0.0115 -0.2193  0.0198  0.0003
23       0.1576 -0.0065 -0.0569  0.0699  0.0005
24       0.0120  0.0190  0.0715  0.0997  0.0001
25       0.1302  0.0196  0.0531  0.0701  0.0001
26      -0.1069  0.0016 -0.1346 -0.0314  0.0001
27      -0.0338  0.0171 -0.0932  0.1429  0.0001
28       0.1627 -0.0008 -0.1546  0.0805  0.0002
29       0.0060 -0.0243 -0.2301 -0.0162  0.0001
30       0.3174  0.0052  0.0297 -0.0302  0.0002
31       0.2440 -0.0020 -0.0328 -0.0072  0.0001
32       0.3908  0.0024  0.0251  0.1069  0.0003
33      -0.1878  0.0213 -0.1933  0.0370  0.0003
34       0.2050  0.0152  0.1219 -0.0005  0.0003
35       0.1527  0.0010 -0.0632  0.0246  0.0003
36       0.1145  0.0022  0.0024  0.0644  0.0005
37       0.0226  0.0223 -0.0516  0.0354  0.0004
38      -0.5829  0.0398 -0.1767 -0.1458  0.0003
39       0.2315  0.0094 -0.0012  0.1521  0.0003
40       0.1004  0.0168  0.0393  0.1003  0.0004
41      -0.3946  0.0357 -0.1134 -0.0402  0.0004
42       0.4944  0.0239  0.2319  0.1309  0.0006
43       0.2549 -0.0138  0.2088  0.0739  0.0005
44      -0.3416 -0.0001  0.0174 -0.3240  0.0037
45       0.6882  0.0163  0.2606  0.2981  0.0015
46       0.5644  0.0361  0.2400  0.3454  0.0009
47       0.1183  0.0003  0.1027  0.0904  0.0007
48      -0.2780  0.0121  0.0746  0.0114  0.0100
49      -0.0533 -0.0169  0.1085 -0.0595  0.0062
50      -0.4771 -0.0098 -0.4315  0.0477  0.0059
51      -0.6707  0.0372 -0.3734 -0.3883  0.0068
52       0.0627  0.0017  0.0755  0.0209  0.0130
53       0.2197 -0.0194  0.1191 -0.1066  0.0131
54       0.0701  0.0162  0.0584  0.0107  0.0133
55      -0.0687  0.0185  0.0182 -0.1413  0.0125

In [225]:
new_funds.drop(columns='VMRXX', inplace=True)

In [226]:
new_funds.cov()

three_funds     VBTLX     VGPMX     VGSLX
three_funds     0.090757 -0.000584  0.033068  0.025116
VBTLX          -0.000584  0.000267  0.000371  0.000205
VGPMX           0.033068  0.000371  0.024573  0.009361
VGSLX           0.025116  0.000205  0.009361  0.014565

In [227]:
new_funds.corr()

three_funds     VBTLX     VGPMX     VGSLX
three_funds     1.000000 -0.118689  0.700234  0.690814
VBTLX          -0.118689  1.000000  0.144621  0.103700
VGPMX           0.700234  0.144621  1.000000  0.494842
VGSLX           0.690814  0.103700  0.494842  1.000000

In [229]:
new_funds_weights = new_funds_mean_excess[0:4].dot(np.linalg.inv(new_funds.cov()))

Computing New weights

In [228]:
# mean excess returns of the new funds
new_funds_mean_excess[0:4]

array([0.06643571, 0.00829286, 0.00259107, 0.01735536])

In [149]:
new_funds_weights

array([ 2.98917612, 44.45949099, -3.76080112, -2.1702469 ])

In [151]:
normalized_new_funds_weights = []
for i in new_funds_weights:
    i = i/sum(new_funds_weights)
    normalized_new_funds_weights.append(i)

## New Weights of new fund series

In [230]:
normalized_new_funds_weights

[0.07199777308272175,
 1.0708583960401215,
 -0.09058325593366552,
 -0.05227291318917738]