In [26]:
import pandas as pd
import numpy as np
from scipy import linalg

## Creatng 56X7 matrix of all returns for all quarters.

In [27]:
df1 = pd.ExcelFile(r'C:\Users\samas\Downloads\NYU Spring 2021-4 data.xlsx')
df2 = pd.read_excel(df1, 'VBTLX', header= 1)
df2.set_index("Unnamed: 0", inplace = True)
df2.dropna(axis = 1, inplace = True)

l = []
for index, row in df2.iterrows():
    current_row = row.values
    l.append(current_row)
l = np.array(l)
l = np.concatenate(l)
df3 = pd.read_excel(df1, 'VWILX', header = 1)
df3.set_index("Unnamed: 0", inplace = True)
df3.dropna(axis = 1, inplace = True)

m = []
for index, row in df3.iterrows():
    current_row = row.values
    m.append(current_row)
m = np.array(m)
m = np.concatenate(m)
df4 = pd.read_excel(df1, 'VGPMX', header = 1)
df4.set_index("Unnamed: 0", inplace = True)
df4.dropna(axis = 1, inplace = True)

n = []
for index, row in df4.iterrows():
    current_row = row.values
    n.append(current_row)
n = np.array(n)
n = np.concatenate(n)
df5 = pd.read_excel(df1, 'VTSAX', header = 1)
df5.set_index("Unnamed: 0", inplace = True)
df5.dropna(axis = 1, inplace = True)

o = []
for index, row in df5.iterrows():
    current_row = row.values
    o.append(current_row)
o = np.array(o)
o = np.concatenate(o)
df6 = pd.read_excel(df1, 'VTRIX', header = 1)

df6.set_index("Unnamed: 0", inplace = True)
df6.dropna(axis = 1, inplace = True)

p = []
for index, row in df6.iterrows():
    current_row = row.values
    p.append(current_row)
p = np.array(p)
p = np.concatenate(p)
df7 = pd.read_excel(df1, 'VGSLX', header = 1)
df7.set_index("Unnamed: 0", inplace = True)
df7.dropna(axis = 1, inplace = True)

q = []
for index, row in df7.iterrows():
    current_row = row.values
    q.append(current_row)
q = np.array(q)
q = np.concatenate(q)
df8 = pd.read_excel(df1, 'VMRXX', header = 1)
df8.set_index("Unnamed: 0", inplace = True)
df8.dropna(axis = 1, inplace = True)

r = []
for index, row in df8.iterrows():
    current_row = row.values
    r.append(current_row)
r = np.array(r)
r = np.concatenate(r)

all_rets = pd.DataFrame(np.column_stack([l,m,n,o,p,q,r]), columns = ['VBTLX', 'VWILX', 'VGPMX', 'VTSAX', 'VTRIX', 'VGSLX', 'VMRXX'])

In [28]:
all_rets

VBTLX   VWILX   VGPMX   VTSAX   VTRIX   VGSLX   VMRXX
0   0.0327 -0.1552 -0.2528 -0.2087 -0.2630 -0.2410  0.0040
1   0.0298  0.3301  0.2319  0.2208  0.1508  0.1346  0.0013
2   0.0061  0.1627  0.0928  0.0920  0.0399  0.0133  0.0003
3   0.0067  0.2226  0.1653  0.1469  0.2357  0.0926  0.0001
4   0.0294  0.1492  0.1004  0.1404  0.0944  0.1728  0.0062
5   0.0307  0.0323  0.0321  0.0409  0.0242  0.0173  0.0062
6   0.0243 -0.0302 -0.0075  0.0109 -0.0125  0.0740  0.0056
7   0.0003  0.1429  0.0703  0.0901  0.0877  0.0062  0.0047
8  -0.0147  0.0339 -0.0930 -0.0060 -0.0063 -0.0811  0.0039
9  -0.0017  0.0071  0.0115  0.0391 -0.0320  0.0883  0.0048
10  0.0003 -0.0151 -0.1469  0.0709  0.0099  0.0052  0.0054
11  0.0161 -0.1476 -0.1346 -0.1426 -0.1201 -0.0644  0.0059
12  0.0091  0.1267  0.1056  0.0579  0.0806  0.0096  0.0021
13  0.0148  0.1026 -0.0183  0.0303  0.0577  0.0161  0.0026
14  0.0073  0.1068  0.0216  0.0454  0.0672  0.0089  0.0029
15  0.0040  0.0413  0.0259  0.0634  0.0490  0.0139  0.0032
16  0.0309 -0.0201  0.3157  0.0094 -0.0051  0.0627  0.0011
17  0.0236  0.0052  0.3484  0.0269  0.0013  0.0680  0.0013
18  0.0041  0.1083  0.0145  0.0440  0.0604 -0.0147  0.0014
19 -0.0317 -0.0670 -0.1630  0.0412 -0.0111 -0.0297  0.0017
20  0.0165  0.0549 -0.0368  0.0179  0.0418  0.0472  0.0002
21 -0.0179  0.0118 -0.0058  0.0008  0.0122 -0.1046  0.0002
22  0.0118 -0.1299 -0.2190 -0.0727 -0.1341  0.0201  0.0003
23 -0.0060  0.0709 -0.0564  0.0626  0.0246  0.0704  0.0005
24  0.0191 -0.0074  0.0716  0.0203 -0.0008  0.0998  0.0001
25  0.0197  0.0314  0.0532  0.0486  0.0503  0.0702  0.0001
26  0.0017 -0.0491 -0.1345 -0.0003 -0.0574 -0.0313  0.0001
27  0.0172 -0.0293 -0.0931  0.0524 -0.0568  0.1430  0.0001
28 -0.0006  0.0312 -0.1544  0.1102  0.0215  0.0807  0.0002
29 -0.0242 -0.0215 -0.2300  0.0279 -0.0003 -0.0161  0.0001
30  0.0054  0.1368  0.0299  0.0627  0.1181 -0.0300  0.0002
31 -0.0019  0.0733 -0.0327  0.1010  0.0698 -0.0071  0.0001
32  0.0027  0.1396  0.0254  0.1291  0.1224  0.1072  0.0003
33  0.0216 -0.0780 -0.1930 -0.0315 -0.0780  0.0373  0.0003
34  0.0155  0.0707  0.1222  0.0624  0.0722 -0.0002  0.0003
35  0.0013  0.0682 -0.0629  0.0018  0.0830  0.0249  0.0003
36  0.0027  0.0327  0.0029  0.0636  0.0187  0.0649  0.0005
37  0.0227  0.0162 -0.0512 -0.0002  0.0070  0.0358  0.0004
38  0.0401 -0.2230 -0.1764 -0.1523 -0.2073 -0.1455  0.0003
39  0.0097  0.0599 -0.0009  0.1214  0.0505  0.1524  0.0003
40  0.0172  0.0255  0.0397  0.0603  0.0150  0.1007  0.0004
41  0.0361 -0.1216 -0.1130 -0.1130 -0.1596 -0.0398  0.0004
42  0.0245  0.1986  0.2325  0.1164  0.1800  0.1315  0.0006
43 -0.0133  0.0725  0.2093  0.1168  0.0661  0.0744  0.0005
44  0.0036 -0.1023  0.0211 -0.1067 -0.1289 -0.3203  0.0037
45  0.0178  0.2711  0.2621  0.1692  0.2494  0.2996  0.0015
46  0.0370  0.1925  0.2409  0.1653  0.2075  0.3463  0.0009
47  0.0010  0.0427  0.1034  0.0584  0.0179  0.0911  0.0007
48  0.0221 -0.0903  0.0846 -0.0948 -0.0829  0.0214  0.0100
49 -0.0107 -0.0166  0.1147 -0.0154 -0.0151 -0.0533  0.0062
50 -0.0039 -0.1974 -0.4256 -0.0852 -0.1886  0.0536  0.0059
51  0.0440 -0.2316 -0.3666 -0.2272 -0.2051 -0.3815  0.0068
52  0.0147  0.0296  0.0885  0.0136  0.0325  0.0339  0.0130
53 -0.0063  0.0888  0.1322  0.0607  0.0833 -0.0935  0.0131
54  0.0295  0.0408  0.0717  0.0156  0.0270  0.0240  0.0133
55  0.0310 -0.0037  0.0307 -0.0332 -0.0193 -0.1288  0.0125

## Assuming the market capitalisation as market weights for each fund


In [29]:
market_cap = np.array([302.9, 71.18, 1.25, 1111, 13.03, 63.89, 40])
market_cap_weights = []
for i in market_cap:
    i = i/sum(market_cap)
    market_cap_weights.append(i)

In [32]:
market_cap_weights = np.array(market_cap_weights)
market_cap_weights

array([0.18892874, 0.04439732, 0.00077967, 0.69296741, 0.00812724,
       0.0398503 , 0.02494932])

## Assuming the risk free rate as 0.0020

In [42]:
excess_rets = all_rets - 0.0020

In [43]:
mean_rets = np.array(excess_rets.mean())
mean_rets

array([0.00913393, 0.02647321, 0.00343214, 0.02549464, 0.01130893,
       0.01819643, 0.00084107])

In [44]:
rets = excess_rets - excess_rets.mean() # demeaned excess returns

In [45]:
cov = rets.cov()

In [46]:
cov

VBTLX     VWILX         VGPMX     VTSAX     VTRIX     VGSLX  \
VBTLX  0.000272 -0.000182  3.667894e-04 -0.000360 -0.000274  0.000075   
VWILX -0.000182  0.013219  1.264802e-02  0.009245  0.011334  0.008395   
VGPMX  0.000367  0.012648  2.455993e-02  0.008690  0.011490  0.009223   
VTSAX -0.000360  0.009245  8.689501e-03  0.008085  0.008468  0.008159   
VTRIX -0.000274  0.011334  1.148989e-02  0.008468  0.010891  0.008195   
VGSLX  0.000075  0.008395  9.222506e-03  0.008159  0.008195  0.014299   
VMRXX  0.000009 -0.000074  5.099286e-07 -0.000089 -0.000064 -0.000126   

              VMRXX  
VBTLX  9.357854e-06  
VWILX -7.431670e-05  
VGPMX  5.099286e-07  
VTSAX -8.873996e-05  
VTRIX -6.442674e-05  
VGSLX -1.257531e-04  
VMRXX  1.361483e-05

## Calculating $$\lambda = \frac{E(r) - rf}{\sigma^2}$$
Asuming rf = 2%

In [47]:
expected_mkt_rets = market_cap_weights.dot(mean_rets)

In [48]:
expected_mkt_rets

0.021408661635962667

In [49]:
market_cap_var = market_cap_weights.dot(cov).dot(market_cap_weights)

In [50]:
market_cap_var

0.005010371810343145

In [53]:
lbd = (expected_mkt_rets - 0.002)/market_cap_var

In [54]:
lbd

3.873696877324844

In [55]:
implied_market_rets = lbd*cov.dot(market_cap_weights)

In [56]:
implied_market_rets

VBTLX   -0.000792
VWILX    0.028641
VGPMX    0.027629
VTSAX    0.024573
VTRIX    0.026116
VGSLX    0.025882
VMRXX   -0.000264
dtype: float64

## Views:
1. VTSAX will have an expected return of 3.5%. 
2. VWILX will outperform VTRIX by 50bps. 
3. VGSLX will outperform VGPMX by 20bps. 
4. Stocks (VWILX, VTSAX) will outperform bonds (VBTLX, VMRXX) by 1.5%. 

In [127]:
stock_weights = np.array([71.18/(71.18+1111), 1111/(71.18+1111)])
bond_weights = np.array([302.9/(302.9+40), 40/(302.9+40)])
stock_rets = stock_weights.dot(np.array([0.028641, 0.024573]))
bond_rets = bond_weights.dot(np.array([-0.000792, -0.000264]))

In [128]:
stock_weights

array([0.0602108, 0.9397892])

In [129]:
bond_weights

array([0.88334791, 0.11665209])

In [153]:
stock_rets- bond_rets

0.02554834522124236

So we are expecting that stocks will outperform by less amount compared to implied market expectations. So this must relatively increase the weights of bonds.

In [130]:
p_mat = np.array([[0,0,0,1,0,0,0], [0,1,0,0,-1,0,0], [0,0,-1,0,0,1,0], [-0.88, 0.06, 0,0.94,0,0,-0.12]])
q_mat = np.array([3.5, 0.5,0.2, 1.5])


In [131]:
var_view_pf = p_mat.dot(cov).dot(p_mat.T)

In [138]:
a = np.zeros((4,4))
np.fill_diagonal(a, np.diag(var_view_pf))

In [139]:
a

array([[0.00808473, 0.        , 0.        , 0.        ],
       [0.        , 0.0014435 , 0.        , 0.        ],
       [0.        , 0.        , 0.02041431, 0.        ],
       [0.        , 0.        , 0.        , 0.00908223]])

## Assuming $\tau$ = 0.05

In [140]:
cov_error = a*0.05

In [141]:
cov_error

array([[4.04236262e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 7.21748805e-05, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.02071532e-03, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.54111724e-04]])

## Computing Expected Returns Using Black-Litterman Formula

 $$p_1 = {[({\tau\Sigma})^{-1} + P\Omega^{-1} P]}^{-1}$$

In [142]:
p1 = np.linalg.inv(0.05*cov) + p_mat.T.dot(np.linalg.inv(cov_error)).dot(p_mat)

In [143]:
p1 = np.linalg.inv(p1)

In [144]:
p1

array([[ 1.22837571e-05,  4.25613653e-06,  2.76316738e-05,
        -3.41253745e-06,  1.37256371e-06,  2.08044892e-05,
         2.59522480e-07],
       [ 4.25613653e-06,  2.67350592e-04,  2.35457960e-04,
         1.49939167e-04,  2.35894966e-04,  1.48551054e-04,
        -7.41957664e-07],
       [ 2.76316738e-05,  2.35457960e-04,  6.57877683e-04,
         1.49536680e-04,  2.27909158e-04,  2.85301898e-04,
         8.16233269e-07],
       [-3.41253745e-06,  1.49939167e-04,  1.49536680e-04,
         1.35180448e-04,  1.42928982e-04,  1.46727391e-04,
        -1.42406618e-06],
       [ 1.37256371e-06,  2.35894966e-04,  2.27909158e-04,
         1.42928982e-04,  2.39660751e-04,  1.52870917e-04,
        -5.56471826e-07],
       [ 2.08044892e-05,  1.48551054e-04,  2.85301898e-04,
         1.46727391e-04,  1.52870917e-04,  4.19016678e-04,
        -2.49325623e-06],
       [ 2.59522480e-07, -7.41957664e-07,  8.16233269e-07,
        -1.42406618e-06, -5.56471826e-07, -2.49325623e-06,
         6.2521971

$$p_2 = {[({\tau\Sigma})^{-1}\pi + P\Omega^{-1}Q]}$$

In [145]:
p_2 = np.linalg.inv(0.05*cov).dot(np.array(implied_market_rets)) + p_mat.T.dot(np.linalg.inv(cov_error)).dot(q_mat) 

In [146]:
p_2

array([-2892.13661015,  7129.24672858,  -195.88061587, 11816.95258803,
       -6926.98833072,   199.02837966,  -394.44530464])

## Expected Returns from portfolio computed using Black Litterman model

In [147]:
expected_BL_rets = p1.dot(p_2)

In [148]:
expected_BL_rets

array([-0.05639098,  2.01521823,  1.71466282,  1.68664969,  1.69264371,
        1.70231781, -0.01991635])

In [149]:
new_weights = np.linalg.inv(lbd*cov).dot(expected_BL_rets)

In [150]:
new_weights

array([  6.65171149,  31.33405943,  -2.68445224,  51.69117348,
       -31.72217915,   2.72508221,   0.90623788])

In [151]:
normalized_new_weights = []
for i in new_weights:
    i = i/sum(new_weights)
    normalized_new_weights.append(i)

In [152]:
b = all_rets.columns
d1 = pd.DataFrame(zip(b, normalized_new_weights, market_cap_weights), columns = ['Ticks', 'Black-Litterman_Weights','Market_Weights'])
d1

Ticks  Black-Litterman_Weights  Market_Weights
0  VBTLX                 0.112929        0.188929
1  VWILX                 0.531973        0.044397
2  VGPMX                -0.045575        0.000780
3  VTSAX                 0.877585        0.692967
4  VTRIX                -0.538562        0.008127
5  VGSLX                 0.046265        0.039850
6  VMRXX                 0.015386        0.024949

## The portfolio given by the black litterman model has more weightage to my views. That is the reason most of the weight is given to VTSAX which I expect would give me 3.5%. And as per my other two views the model allocated less to VGPMX and VTRIX  and more to VWILX and VGSLX compared to the market cap weights. And the bonds VBTLX and VMRXX are allocated decent amount of weights since the stocks are expected to outperform by a less amount as per my view.

## The Black Litterman model is helpful in combining the investors personal views and taking into consideration, the market implied returns which resuls in a more balanced and reliable portfolio compared to mean-variance optimization.